#!/bin/bash

#Script para Inserción, modificación y eliminación de objetos en OpenLDAP.
#Autor : Rubén Pujante
#--------------------------------------------------------------------------------------------------------------------------

# ----- Colores
	
		nc='\033[0m' 		#Sin color
		r='\033[0;31m'		#Rojo
		g='\033[0;32m'		#Verde
		y='\033[1;33m'		#Amarillo
		b='\033[1;34m'		#Azul

# ----- Variables

		LDAP_SERVER="ldap://192.168.100.10"
		ADMIN_DN="cn=admin,dc=servidor25,dc=local"
		ADMIN_PW="ruben2024"
		BASE_DN="dc=servidor25,dc=local"

# ----- Archivos LDIF.
		LDIF_US="/etc/ldap/usuario.ldif"
		LDIF_GR="/etc/ldap/grupo.ldif"
		LDIF_OU="/etc/ldap/ou.ldif"
		
#--------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------- FUNCIONES PARA USUARIOS ----------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------

# ----- Función para obtener último UIDNumber en uso.
#--------------------------------------------------------------------------------------------------------------------------
		obtener_ultimouid(){

			ultimo_uid=$(ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=usuarios,$BASE_DN" "(objectClass=posixAccount)" uidNumber | \

				awk '/^uidNumber:/ {print $2}' | sort -n | tail -n 1)

		
		# ----- Con ldapsearch... buscamos, autenticándonos como admin en el servidor, como base de búsqueda, la OU:usuarios, y con filtro : possixAccount(es decir cuentas de usuario), el atributos UIDNumber

		# ----- Pasamos la salida de la búsqueda a 'awk' para que busque las líneas que comienzan por uidNumber (^uidNumber:)

		# ----- Con {print $2} conseguimos el segundo campo de las líneas que comienzan por uidNumber, es decir el propio uidNumber.

		# ----- Con 'sort -n' ordena la lista obtenida de forma numérica.

		# ----- Con 'tail -n 1' obtenemos la última línea de la salida de 'sort', consiguiendo así el ultimo uidNumber.

		# ----- Una  vez obtenido el último uidNumber lo asignamos a la variable ultimo_uid 


# ----- Utilizar el último uidnumber y calcular el siguiente


							if [ -z "$ultimo_uid" ]; then 			# ----- Si la variable $ultimo_uid esta vacía

								nuevo_uid=20000 					# -----  Asignamos el uidNumber 20000

							else

								nuevo_uid=$((ultimo_uid +1))		# ----- Si no está vacía, a su contenido, el último uidNumber, le sumamos 1
																	# ----- Y lo establecemos  en la variable $nuevo_uid
							fi

							echo "$nuevo_uid"
			}

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para comprobar si existe el usuario a crear.
#--------------------------------------------------------------------------------------------------------------------------
		existe_usuario(){

			local uid=$1	

				ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=usuarios,$BASE_DN" "(uid=$uid)" | grep -q "^dn:"
		}

							# ----- Declaramos una variable local 'uid' y le asignamos el valor del parámetro introducido a la función.

							# ----- Con ldapsearch... buscamos si el uid introducido por el usuario tiene el mismo valor que alguno del servidor.

							# ----- Con grep -q "^dn:" Sin imprimir nada por pantalla (-q) busca las líneas que coinciden con dn.

							# ----- Si grep encuentra coincidencias devolverá un 0, si no un 1.

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para crear un nuevo usuario.
#--------------------------------------------------------------------------------------------------------------------------
		crear_usuario(){
		
# ---- Solicitud de atributos

			echo ""
			read -p " Introduzca nombre del usuario(cn): " cn

			echo ""
			read -p " Introduzca apellido(sn): " sn

			echo ""
			read -p " Introduzca el nombre de usuari(uid): " uid

# ----- Comprobar si el usuario introducido existe

				if existe_usuario "$uid"; then									# ----- Pasamos $uid a la funcion existe_usuario 

					echo ""
					echo -e "${r} ERROR : El usuario '$uid' ya existe."			# ----- Si existe no muestra el error, si no continúa la solicitud de datos.

					return
				fi


			echo ""
			read -p " Introduzca correo electrónico: " mail

			echo ""
			read -p " Contraseña: " passwd

			uid_number=$(obtener_ultimouid) 						# ----- Utilizamos la función obtener_ultimouid y le asignamos el ultimo uidNumer+1 a uidNumber

	
# ----- Creación de archivo .ldif 									# ----- Creamos el archivo con el contenido introducido por el usuario y el nuevo uidNumber calculado

			cat <<-EOF > $LDIF_US
					dn: uid=$uid,ou=usuarios,$BASE_DN
					objectClass: inetOrgPerson
					objectClass: posixAccount
					objectClass: top
					cn: $cn
					sn: $sn
					uid: $uid
					mail: $mail
					userPassword: $passwd
					uidNumber: $uid_number
					gidNumber: 10000
					loginShell: /bin/bash
					homeDirectory: /home/$uid
				EOF

			echo ""
			echo -e "${g}Archivo usuario.ldif procesado con éxito. ${nc}"
	
# ----- Añadir usuario a LDAP

			ldapadd -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$LDIF_US" > /dev/null 
	

# ----- Verificación si el comando anterior se ha ejecutado correctamente.  

				if [ $? -eq 0 ]; then
					echo ""
					echo -e "${g}Nuevo usuario creado correctamente.${nc}"

				else
					echo""
					echo -e "${r}Error al crear el nuevo usuario"${nc}
				fi
		   
		}

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para modificar un usuario.
#--------------------------------------------------------------------------------------------------------------------------
		modificar_usuario(){

			CAMBIOS_FILE="cambios.ldif"

# ----- Si el archivo cambios.ldif no existe crearlo.
			
			if [ ! -f "$CAMBIOS_FILE" ]; then
				touch "$CAMBIOS_FILE"
			fi

# ----- Introducir uid como parámetro de búsqueda.			

			echo ""
			read -p " Introduce el nombre de usuario a modificar : " uid

# ----- Verificar que el usuario existe antes de eliminar.
    	
    			if ! existe_usuario "$uid"; then
        			echo""
        			echo -e ${r}"Error: El usuario '$uid' no existe.${nc}"
        			return
    			fi

# ----- Atributos a modificar
			
			echo ""
			echo -e "${y} Atributos disponibles para modificar: cn, sn, userPassword, gidNumber.${nc}"

			echo ""
			read -p "  Introduzca el atributo que desea modificar: " atributo

			echo ""
			read -p "  Introduzca el nuevo valor para $atributo : " nuevo_valor

# ----- Creación del archivo de modificación.

			echo "dn: uid=$uid,ou=usuarios,$BASE_DN" > "$CAMBIOS_FILE"
			echo "changetype: modify" >> "$CAMBIOS_FILE"
			echo "replace: $atributo" >> "$CAMBIOS_FILE"
			echo "$atributo: $nuevo_valor" >> "$CAMBIOS_FILE" 

			echo ""
			echo -e "${g}Procesando archivo cambios.ldif... ${nc}"
			echo ""
			
# ----- Modificación de los atributos del usuario leyendo archivo cambios.ldif.

			ldapmodify -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$CAMBIOS_FILE"

# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
    
	    		if [ $? -eq 0 ]; then
	        		
	        		echo -e "${g}Atributo del usuario '$uid' modificado exitosamente.${nc}"
	    			
	    			else
	    				echo""
	        			echo -e "${r}Error al modificar el atributo del usuario '$uid'.${nc}"
	    		fi

    		> "$CAMBIOS_FILE"

		}

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para eliminar un usuario.
#--------------------------------------------------------------------------------------------------------------------------
		eliminar_usuario(){

			read -p " Introduzca el nombre de usuario (uid) a eliminar: " uid

# ----- Verificar que el usuario existe antes de eliminar
    	
    			if ! existe_usuario "$uid"; then
        			echo""
        			echo -e ${r}"Error: El usuario '$uid' no existe.${nc}"
        			return
    			fi

# ----- Eliminar usuario de LDAP
    
    		ldapdelete -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" "uid=$uid,ou=usuarios,$BASE_DN"
    
# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
    
	    		if [ $? -eq 0 ]; then
	        		
	        		echo ""
	        		echo -e "${g}Usuario eliminado exitosamente.${nc}"
	    			
	    			else
	    				echo""
	        			echo -e "${r}Error al eliminar el usuario.${nc}"
	    		fi
		}

#--------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------- FUNCIONES PARA GRUPOS ------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------

# ----- Función para obtener último GUIDNumber en uso.
#--------------------------------------------------------------------------------------------------------------------------

			obtener_ultimoguid(){

				ultimo_guid=$(ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=grupos,$BASE_DN" "(objectClass=group)" guidNumber | \

					awk '/^guidNumber:/ {print $2}' | sort -n | tail -n 1)

#--------------------------------------------------------------------------------------------------------------------------
# ----- Utilizar el último guidnumber y calcular el siguiente. 


							if [ -z "$ultimo_guid" ]; then 			
								nuevo_guid=20000 					

							else

								nuevo_guid=$((ultimo_guid +1))		

							fi

							echo "$nuevo_guid"
			}

# ----- Las funciones anteriores se comportan de la misma manera que las utilizadas en el apartado de usuario.


#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para comprobar si existe el grupo a crear.
#--------------------------------------------------------------------------------------------------------------------------

		existe_grupo(){

			local guid=$1	

				ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=grupos,$BASE_DN" "(guid=$guid)" | grep -q "^dn:"
		}

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para crear un nuevo grupo.
#--------------------------------------------------------------------------------------------------------------------------
		crear_grupo(){

# ---- Solicitud de atributos

			echo ""
			read -p " Introduzca nombre para el nuevo grupo(cn): " guid

# ----- Comprobar si el grupo introducido existe

				if existe_grupo "$guid"; then									

					echo ""
					echo -e "${r} ERROR : El grupo '$guid' ya existe."			

					return
				fi

# ----- Creación de archivo .ldif 

			cat <<-EOF > $LDIF_GR
					dn: uid=$guid,ou=usuarios,$$BASE_DN
					objectClass: group
					cn: $guid
					guidNumber: $nuevo_guid	
				EOF

			echo "${g}Archivo grupo.ldif procesado con éxito. ${nc}"

# ----- Añadir grupo a LDAP

			ldapadd -x -D "$ADMIN_DN" -W -f "$LDIF_GR"

# ----- Verificación si el comando anterior se ha ejecutado correctamente.  

				if [ $? -eq 0 ]; then
					echo ""
					echo -e "${g}Nuevo grupo creado correctamente.${nc}"

				else
					echo""
					echo -e "${r}Error al crear el nuevo grupo"${nc}
				fi
		   
		}
		
#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para modificar un grupo
#--------------------------------------------------------------------------------------------------------------------------
		modificar_grupo(){

			CAMBIOS_FILE="cambios.ldif"

# ----- Si el archivo cambios.ldif no existe crearlo.
			
			if [ ! -f "$CAMBIOS_FILE" ]; then
				touch "$CAMBIOS_FILE"
			fi

# ----- Introducir guid como parámetro de búsqueda.			

			echo ""
			read -p " Introduce el guid del grupo a modificar : " guid

# ----- Verificar que el grupo existe antes de eliminar.
    	
    			if ! existe_grupo "$guid"; then
        			echo""
        			echo -e ${r}"Error: El grupo '$guid' no existe.${nc}"
        			return
    			fi

# ----- Atributos a modificar
			
			echo ""
			echo -e "${y} Atributos disponibles para modificar: cn, sn, gidNumber.${nc}"

			echo ""
			read -p "  Introduzca el atributo que desea modificar: " atributo

			echo ""
			read -p "  Introduzca el nuevo valor para $atributo : " nuevo_valor

# ----- Creación del archivo de modificación.

			echo "dn: guid=$guid,ou=grupos,$BASE_DN" > "$CAMBIOS_FILE"
			echo "changetype: modify" >> "$CAMBIOS_FILE"
			echo "replace: $atributo" >> "$CAMBIOS_FILE"
			echo "$atributo: $nuevo_valor" >> "$CAMBIOS_FILE" 

			echo ""
			echo -e "${g}Procesando archivo cambios.ldif... ${nc}"
			echo ""
			
# ----- Modificación de los atributos del usuario leyendo archivo cambios.ldif.

			ldapmodify -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$CAMBIOS_FILE"

# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
    
	    		if [ $? -eq 0 ]; then
	        		
	        		echo -e "${g}Atributo del grupo '$guid' modificado exitosamente.${nc}"
	    			
	    			else
	    				echo""
	        			echo -e "${r}Error al modificar el atributo del grupo '$guid'.${nc}"
	    		fi

    		> "$CAMBIOS_FILE"

		}

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para eliminar un grupo.
#--------------------------------------------------------------------------------------------------------------------------
		eliminar_grupo(){

			read -p " Introduzca el nombre del grupo (guid) a eliminar: " guid

# ----- Verificar que el grupo existe antes de eliminar
    	
    			if ! existe_grupo "$guid"; then
        			echo""
        			echo -e ${r}"Error: El grupo '$guid' no existe.${nc}"
        			return
    			fi

# ----- Eliminar grupo de LDAP

			echo ""
			echo -e "${y}Está apunto de eliminar el grupo.¿Esta seguro? (s/n). ${nc}" respuesta

			if [[ $respuesta =~ sS ]];then
    
    		ldapdelete -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" "guid=$guid,ou=grupos,$BASE_DN"

    		else
    
# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
    
	    		if [ $? -eq 0 ]; then
	        		
	        		echo ""
	        		echo -e "${g}Grupo eliminado exitosamente.${nc}"
	    			
	    			else
	    				echo""
	        			echo -e "${r}Error al eliminar el grupo.${nc}"
	    		fi
		}
		
#--------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------- FUNCIONES PARA OU ----------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------

# ----- Función para la creación de unidades organizativas.
#--------------------------------------------------------------------------------------------------------------------------
		crear_ou(){

			# ---- Solicitud de atributos

			echo ""
			read -p " Introduzca nombre para la nueva unidad organizativa(ou): " ou

# ----- Comprobar si la OU introducida existe

				if existe_ou "$ou"; then									

					echo ""
					echo -e "${r} ERROR : La ou '$ou' ya existe."			

					return
				fi

# ----- Creación de archivo .ldif 

			cat <<-EOF > $LDIF_OU
					dn: ,$$BASE_DN
					objectClass: ou
					cn: 
						
				EOF

			echo "${g}Archivo ou.ldif procesado con éxito. ${nc}"

# ----- Añadir ou a LDAP

			ldapadd -x -D "$ADMIN_DN" -W -f "$LDIF_OU"

# ----- Verificación si el comando anterior se ha ejecutado correctamente.  

				if [ $? -eq 0 ]; then
					echo ""
					echo -e "${g}Nueva unidad organizativa creada correctamente.${nc}"

				else
					echo""
					echo -e "${r}Error al crear la nueva unidad organizativa"${nc}
				fi
		   
		}
#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para modificar OU.
#--------------------------------------------------------------------------------------------------------------------------
		modificar_ou(){
			
			CAMBIOS_FILE="cambios.ldif"

# ----- Si el archivo cambios.ldif no existe crearlo.
			
			if [ ! -f "$CAMBIOS_FILE" ]; then
				touch "$CAMBIOS_FILE"
			fi

# ----- Introducir guid como parámetro de búsqueda.			

			echo ""
			read -p " Introduce el nombre de la OU a modificar : " ou

# ----- Verificar que el grupo existe antes de eliminar.
    	
    			if ! existe_ou "$ou"; then
        			echo""
        			echo -e ${r}"Error: La OU '$ou' no existe.${nc}"
        			return
    			fi

# ----- Atributos a modificar
			
			echo ""
			echo -e "${y} Atributos disponibles para modificar: ${nc}"

			echo ""
			read -p "  Introduzca el atributo que desea modificar: " atributo

			echo ""
			read -p "  Introduzca el nuevo valor para $atributo : " nuevo_valor

# ----- Creación del archivo de modificación.

			echo "dn: ou=grupos,$BASE_DN" > "$CAMBIOS_FILE"
			echo "changetype: modify" >> "$CAMBIOS_FILE"
			echo "replace: $atributo" >> "$CAMBIOS_FILE"
			echo "$atributo: $nuevo_valor" >> "$CAMBIOS_FILE" 

			echo ""
			echo -e "${g}Procesando archivo cambios.ldif... ${nc}"
			echo ""
			
# ----- Modificación de los atributos del usuario leyendo archivo cambios.ldif.

			ldapmodify -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$CAMBIOS_FILE"

# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
    
	    		if [ $? -eq 0 ]; then
	        		
	        		echo -e "${g}Atributo de la OU '$ou' modificado exitosamente.${nc}"
	    			
	    			else
	    				echo""
	        			echo -e "${r}Error al modificar el atributo de la OU '$ou'.${nc}"
	    		fi

    		> "$CAMBIOS_FILE"

		}
#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para eliminar OU.
#--------------------------------------------------------------------------------------------------------------------------
		eliminar_ou(){
			read -p " Introduzca el nombre de la unidad organizativa(OU) a eliminar: " ou

# ----- Verificar que la OU existe antes de eliminar
    	
    			if ! existe_ou "$ou"; then
        			echo""
        			echo -e ${r}"Error: La OU '$ou' no existe.${nc}"
        			return
    			fi

# ----- Eliminar grupo de LDAP

			echo ""
			echo -e "${y}Está apunto de eliminar la OU $ou. ¿Esta seguro? (s/n). ${nc}" respuesta

			if [[ $respuesta =~ sS ]];then
    
    		ldapdelete -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" "ou=$ou,$BASE_DN"

    		else
    
# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
    
	    		if [ $? -eq 0 ]; then
	        		
	        		echo ""
	        		echo -e "${g}Unidad organizativa eliminada exitosamente.${nc}"
	    			
	    			else
	    				echo""
	        			echo -e "${r}Error al eliminar la unidad organizativa.${nc}"
	    		fi
		}
#--------------------------------------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------- Menú selección creación de objetos ---------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------			
		crear_objeto(){

			while true; do
			    	echo ""
					echo -e "${y}Seleccione el tipo de objeto a crear : ${nc}"

						echo ""
						echo "  1. Usuario"
						echo "  2. Grupo"
						echo "  3. Unidad Organizativa"
						echo "  4. Volver al menú principal"
						echo ""
						read -p "Seleccione una opción [1-4] : " tipo

							case $tipo in 

								1)
									crear_usuario
									;;
								2)
									crear_grupo
									;;
				        		3)
									crear_ou
									;;
								4)
									echo -e "${y}Saliendo...${nc}"; 
									exit 0
									;;
								*)
									echo "Opción inválida"
									;;
							esac
			done

		}
#--------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------ Menú selección modificación de objetos ---------------------------------------
#--------------------------------------------------------------------------------------------------------------------------	        
		modificar_objeto(){

			while true; do  

					echo ""
					echo -e "${y}Seleccione el tipo de objeto a modificar : ${nc}"

						echo ""
						echo "  1. Usuario"
						echo "  2. Grupo"
						echo "  3. Unidad Organizativa"
						echo "  4. Volver al menú principal"
						echo ""
						read -p "Seleccione una opción [1-4] : " tipo

							case $tipo in 

								1)
									modificar_usuario
									;;
								2)
									modificar_grupo
									;;
				        		3)
									modificar_ou
									;;
								4)
									return
									;;
								*)
									echo "Opción inválida"
									;;
							esac
			done

		}
#--------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------- Menú selección eliminación de objetos -----------------------------------------	
#--------------------------------------------------------------------------------------------------------------------------	              
		eliminar_objeto(){

			while true; do

					echo""
					echo -e "${y}Seleccione el tipo de objeto a eliminar : ${nc}"
					echo""

						echo "  1. Usuario"
						echo "  2. Grupo"
						echo "  3. Unidad Organizativa"
						echo "  4. Volver al menú principal"
						echo""
						read -p "Seleccione una opción [1-4] : " tipo

							case $tipo in 

								1)
									eliminar_usuario
									;;
								2)
									eliminar_grupo
									;;
				        		3)
									eliminar_ou
									;;
								4)
									return
									;;
								*)
									echo "Opción inválida"
									;;
							esac
			done

		}
#--------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------------ MENÚ PRINCIPAL ---------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------

			while true; do
					
					echo ""
					echo -e "${b}================================================="

						echo -e "   MENÚ DE ADMINISTRACIÓN DE SERVIDOR OpenLDAP"

					echo -e "=================================================${nc}"

						echo ""
						echo -e " ${y}Seleccione una opción:${nc}"
						echo ""
						echo "  1. Agregar objeto"
						echo "  2. Modificar objeto"
						echo "  3. Eliminar objeto"
						echo "  4. Salir"
						echo ""
						read -p  "Seleccione una opción [1-4] : " opcion


							case $opcion in

								1)
									crear_objeto
									;;
								2)
									modificar_objeto
									;;
								3)
									eliminar_objeto
									;;
							    4)
									echo "Saliendo..."
									exit 0
									;;
							    *)
							        echo "Opción inválida"
							        ;;
							esac

			done
