#!/bin/bash

#Script para Inserción, modificación y eliminación de objetos en OpenLDAP.
#Autor : Rubén Pujante
#--------------------------------------------------------------------------------------------------------------------------

# ----- Colores
	
		nc='\033[0m' 		#Sin color
		r='\033[0;31m'		#Rojo
		g='\033[0;32m'		#Verde
		y='\033[1;33m'		#Amarillo
		b='\033[1;34m'		#Azul

# ----- Variables

		LDAP_SERVER="ldap://192.168.100.10"
		ADMIN_DN="cn=admin,dc=servidor25,dc=local"
		ADMIN_PW="ruben2024"
		BASE_DN="dc=servidor25,dc=local"

# ----- Archivos LDIF.
		LDIF_US="/etc/ldap/usuario.ldif"
		LDIF_GR="/etc/ldap/grupo.ldif"
		LDIF_OU="/etc/ldap/ou.ldif"
		
#--------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------- FUNCIONES PARA USUARIOS ----------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------

# ----- Función para obtener último UIDNumber en uso.
#--------------------------------------------------------------------------------------------------------------------------
	obtener_ultimouid(){
			ultimo_uid=$(ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=usuarios,$BASE_DN" "(objectClass=posixAccount)" uidNumber | \
				awk '/^uidNumber:/ {print $2}' | sort -n | tail -n 1)

		
			# ----- Con ldapsearch... buscamos, autenticándonos como admin en el servidor, como base de búsqueda, la OU:usuarios, y con filtro : possixAccount(es decir cuentas de usuario), el atributos UIDNumber

			# ----- Pasamos la salida de la búsqueda a 'awk' para que busque las líneas que comienzan por uidNumber (^uidNumber:)

			# ----- Con {print $2} conseguimos el segundo campo de las líneas que comienzan por uidNumber, es decir el propio uidNumber.

			# ----- Con 'sort -n' ordena la lista obtenida de forma numérica.

			# ----- Con 'tail -n 1' obtenemos la última línea de la salida de 'sort', consiguiendo así el ultimo uidNumber.

			# ----- Una  vez obtenido el último uidNumber lo asignamos a la variable ultimo_uid 

#--------------------------------------------------------------------------------------------------------------------------
	# ----- Utilizar el último uidnumber y calcular el siguiente
#--------------------------------------------------------------------------------------------------------------------------

							if [ -z "$ultimo_uid" ]; then 			# ----- Si la variable $ultimo_uid esta vacía
								nuevo_uid=20000 					# -----  Asignamos el uidNumber 20000
							else
								nuevo_uid=$((ultimo_uid +1))		# ----- Si no está vacía, a su contenido, el último uidNumber, le sumamos 1										# ----- Y lo establecemos  en la variable $nuevo_uid
							fi

							echo "$nuevo_uid"
			}
#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para comprobar si existe el usuario a crear.
#--------------------------------------------------------------------------------------------------------------------------
	existe_usuario(){
			local uid=$1	
				ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=usuarios,$BASE_DN" "(uid=$uid)" | grep -q "^dn:"
		}

							# ----- Declaramos una variable local 'uid' y le asignamos el valor del parámetro introducido a la función.

							# ----- Con ldapsearch... buscamos si el uid introducido por el usuario tiene el mismo valor que alguno del servidor.

							# ----- Con grep -q "^dn:" Sin imprimir nada por pantalla (-q) busca las líneas que coinciden con dn.

							# ----- Si grep encuentra coincidencias devolverá un 0, si no un 1.

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para crear un nuevo usuario.
#--------------------------------------------------------------------------------------------------------------------------
	crear_usuario(){
		echo ""
		echo -e "${b} Creación de un usuario${nc}"
		echo ""

		# ----- Solicitar información al usuario 
		
		# ---- Solicitud de atributos
					echo ""
					read -p " Introduzca nombre de pila usuario(cn): " cn

					echo ""
					read -p " Introduzca apellido(sn): " sn

					echo ""
					read -p " Introduzca el nombre de usuario(uid): " uid

		# ----- Comprobar si el usuario introducido existe

						if existe_usuario "$uid"; then									# ----- Pasamos $uid a la funcion existe_usuario 
							echo ""
							echo -e "${r} ERROR : El usuario '$uid' ya existe."			# ----- Si existe muestra el error.
							return
						fi

		# ---- Continuación de solicitud de atributos
					echo ""
					read -p " Introduzca correo electrónico: " mail

					echo ""
					read -p " Contraseña: " passwd

					echo ""
					read -p " gidNumber: " gid_number
					echo ""

		# ----- Llamada a la función para calcular uidNumber
					uid_number=$(obtener_ultimouid) 						# ----- Utilizamos la función obtener_ultimouid y le asignamos el ultimo uidNumer+1 a uidNumber

			
		# ----- Creación de archivo .ldif
				echo "" 													# ----- Creamos el archivo con el contenido introducido por el usuario y el nuevo uidNumber calculado
				echo -e "${y} Creando archivo usuario.ldif...${nc}"

					cat <<-EOF > $LDIF_US
							dn: uid=$uid,ou=usuarios,$BASE_DN
							objectClass: inetOrgPerson
							objectClass: posixAccount
							objectClass: top
							cn: $cn
							sn: $sn
							uid: $uid
							mail: $mail
							userPassword: $passwd
							uidNumber: $uid_number
							gidNumber: $gid_number
							loginShell: /bin/bash
							homeDirectory: /home/$uid
						EOF

		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  			
					if [ $? -eq 0 ]; then
							echo ""
							echo -e "${g}Archivo usuario.ldif creado con éxito. ${nc}"
						else
							echo""
							echo -e "${r}Error al crear el archivo"${nc}
						fi		
		
		# ----- Añadir usuario a LDAP
					ldapadd -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$LDIF_US" > /dev/null 
			
		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
						if [ $? -eq 0 ]; then
							echo ""
							echo -e "${g}Nuevo usuario creado correctamente.${nc}"
						else
							echo""
							echo -e "${r}Error al crear el nuevo usuario"${nc}
						fi		   
	}
#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para modificar un usuario.
#--------------------------------------------------------------------------------------------------------------------------
	modificar_usuario(){
		echo ""
		echo -e "${b} Modificación de un usuario${nc}"
		echo ""

			CAMBIOS_FILE="cambios.ldif"

		# ----- Si el archivo cambios.ldif no existe crearlo.
					if [ ! -f "$CAMBIOS_FILE" ]; then
						touch "$CAMBIOS_FILE"
					fi

		# ----- Introducir uid como parámetro de búsqueda.		
					echo ""
					read -p " Introduce el nombre de usuario a modificar : " uid

		# ----- Verificar que el usuario existe antes de modificar.	
		    			if ! existe_usuario "$uid"; then
		        			echo""
		        			echo -e "${r}Error: El usuario '$uid' no existe.${nc}"
		        			return
		    			fi

		# ----- Menú de atributos posibles de modificar 						Hemos controlado las opciones para que atributos como el uidNumber no puedan ser modificados.
					echo ""
					echo -e "${y} Atributos disponibles para modificar${nc}"
					echo ""
								echo "  1) cn (Nombre completo)"
								echo ""
								echo "  2) sn (Apellido)"
								echo ""
								echo "  3) mail (Correo electrónico)"
								echo ""
								echo "  4) userPassword (Contraseña)"
								echo ""
								echo "  5) telephoneNumber (Número de teléfono)"
								echo ""
								echo "  6) address (Dirección)"
								echo ""
								echo "  7) gidNumber (Identificador grupo)"
								echo ""

		# ----- Leer la opción elegida por el usuario
					read -p "  Introduzca el número del atributo que desea modificar: " opcion
					echo ""

		# ----- Asignar el atributo basado en la opción elegida
								case "$opcion" in
								    1)
								        atributo="cn"
								        ;;
								    2)
								        atributo="sn"
								        ;;
								    3)
								        atributo="mail"
								        ;;
								    4)
								        atributo="userPassword"
								        ;;
								    5)
								        atributo="telephoneNumber"
								        ;;
								    6)
								        atributo="address"
								        ;;
								    7)
								        atributo="gidNumber"
								        ;;
								    *)
								        echo -e "${r}Error: Opción no válida.${nc}"
								        return
								        ;;
								esac
					echo ""
			
		# ----- Solicitud nuevo valor del atributo
				read -p "  Introduzca el nuevo valor para $atributo : " nuevo_valor

		# ----- Creación del archivo de modificación.
					echo "dn: uid=$uid,ou=usuarios,$BASE_DN" > "$CAMBIOS_FILE"
					echo "changetype: modify" >> "$CAMBIOS_FILE"
					echo "replace: $atributo" >> "$CAMBIOS_FILE"
					echo "$atributo: $nuevo_valor" >> "$CAMBIOS_FILE" 

					echo ""
					echo -e "${g}Procesando archivo cambios.ldif... ${nc}"
					echo ""
					

		# ----- Modificación de los atributos del usuario leyendo archivo cambios.ldif.
					ldapmodify -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$CAMBIOS_FILE"

		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
			    		if [ $? -eq 0 ]; then
			        		
			        		echo -e "${g}Atributo del usuario '$uid' modificado.${nc}"
			    			echo ""
			    		else
			    			echo""
			        		echo -e "${r}Error al modificar el atributo del usuario '$uid'.${nc}"
			    		fi

		    		> "$CAMBIOS_FILE"
	}
#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para eliminar un usuario.
#--------------------------------------------------------------------------------------------------------------------------
	eliminar_usuario(){
			echo ""
			echo -e "${b} Eliminación de un usuario${nc}"
			echo ""

		# ----- Solicitar información al usuario 
			
			read -p " Introduzca el nombre de usuario(uid) a eliminar: " uid

		# ----- Verificar que el usuario existe antes de eliminar
		    			if ! existe_usuario "$uid"; then
		        			echo""
		        			echo -e "${r} Error: El usuario '$uid' no existe.${nc}"
		        			return
		    			fi

		# ----- Pregunta de verificación de la eliminación.
					echo ""
					read -p " ¿Está seguro que desea eliminar el usuario '$uid'? (s/n) : " respuesta

							if [[ "$respuesta" =~ ^[Ss]$ ]];then								
		# ----- Eliminar usuario de LDAP
		    					ldapdelete -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" "uid=$uid,ou=usuarios,$BASE_DN"
								echo ""
								echo -e "${g} Usuario eliminado.${nc}"
							else
								echo""
			        			echo -e "${r}Error al eliminar el usuario.${nc}"
							fi
	}
#--------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------- FUNCIONES PARA GRUPOS ------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------

# ----- Función para comprobar si existe el grupo.
#--------------------------------------------------------------------------------------------------------------------------
	existe_grupo(){
		local cn=$1	
			ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "$GRUPOS,$BASE_DN" "(cn=$cn)" | grep -q "^cn: $cn"
		}

# ----- Función para obtener último GUIDNumber en uso.
#--------------------------------------------------------------------------------------------------------------------------
		GRUPOS="ou=grupos"

	obtener_ultimogid(){
		ultimo_gid=$(ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "$GRUPOS,$BASE_DN" "(objectClass=posixGroup)" gidNumber | \
			awk '/^gidNumber:/ {print $2}' | sort -n | tail -n 1)

#--------------------------------------------------------------------------------------------------------------------------
# ----- Utilizar el último guidnumber y calcular el siguiente. 
#--------------------------------------------------------------------------------------------------------------------------
				if [ -z "$ultimo_gid" ]; then 
					nuevo_gid=15000	
				else
					nuevo_gid=$((ultimo_gid +1))
				fi
				echo "$nuevo_gid"
			}

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para verificar que el gid es válido
#--------------------------------------------------------------------------------------------------------------------------
					if [ $? -ne 0 ]; then
						echo -e "${r} Error al obtener gidNumber.${nc}"
						return
					fi

						# Validar que gid_number sea un número
					if ! [[ "$gid_number" =~ ^[0-9]+$ ]]; then
						echo -e "${r} Error: gidNumber generado no es válido.${nc}"
					
					fi

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para crear un nuevo grupo.
#--------------------------------------------------------------------------------------------------------------------------
	crear_grupo(){
			echo ""
			echo -e "${b} Creación de un grupo${nc}"
			echo ""

		# ---- Solicitud de atributos
					echo ""
					read -p " Introduzca nombre para el nuevo grupo(cn): " cn

		# ----- Comprobar si el grupo introducido existe
						if existe_grupo "$cn"; then									
							echo ""
							echo -e "${r} ERROR : El grupo '$cn' ya existe."			
							return
						fi

		# ----- Llamada a la función para calcular uidNumber
					gid_number=$(obtener_ultimogid) 
					echo ""
					echo " Nuevo gidNumber generado: $gid_number"

		# ----- Creación de archivo grupo.ldif 
				echo "dn: cn=$cn,ou=grupos,$BASE_DN" > $LDIF_GR
				echo "objectClass: posixGroup" >> $LDIF_GR
				echo "cn: $cn" >> $LDIF_GR		
				echo "gidNumber: $gid_number" >> $LDIF_GR
					
		# ----- 				
				echo ""
				echo -e "${g}Procesando archivo grupo.ldif... ${nc}"
				echo ""
				sleep 1	
			
		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  			
					if [ $? -eq 0 ]; then
						echo ""
						echo -e "${g} Archivo grupo.ldif creado con éxito. ${nc}"
						echo ""
					else
						echo""
						echo -e "${r} Error al crear el archivo"${nc}
					fi			

		# ----- Muestra el contenido del archivo grupo.ldif para comprobar el formato.
						echo "Contenido de grupo.ldif:"
						cat "$LDIF_GR"

		# ----- Añadir grupo a LDAP
					ldapadd -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$LDIF_GR"

		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
						if [ $? -eq 0 ]; then
							echo ""
							echo -e "${g}Nuevo grupo creado correctamente.${nc}"
						else
							echo""
							echo -e "${r}Error al crear el nuevo grupo"${nc}
						fi

					> "$LDIF_GR"		   
	}		
#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para modificar un grupo
#--------------------------------------------------------------------------------------------------------------------------
	modificar_grupo(){

			echo ""
			echo -e "${b} Modificación de un grupo${nc}"
			echo ""
			
			CAMBIOS_FILE="/etc/ldap/cambios.ldif"

		# ----- Si el archivo cambios.ldif no existe crearlo.
					if [ ! -f "$CAMBIOS_FILE" ]; then
						touch "$CAMBIOS_FILE"
					fi

		# ----- Introducir cn como parámetro de búsqueda.	
					echo ""
					read -p " Introduce el nombre(cn) del grupo a modificar : " cn

		# ----- Verificar que el grupo existe antes de eliminar.
		    			if ! existe_grupo "$cn"; then
		        			echo""
		        			echo -e "${r} Error: El grupo '$cn' no existe.${nc}"
		        			return
		    			fi

		# ----- Menú de atributos posibles de modificar 						
					echo ""
					echo -e "${y} Atributos disponibles para modificar${nc}"
					echo ""
								echo "  1) CN (Nombre completo)"
								echo ""
								echo "  2) OU (Unidad Organizativa)"
								echo ""
								echo "  3) Descripción (description)"
							

		# ----- Leer la opción elegida por el usuario
					read -p "  Introduzca el número del atributo que desea modificar(1-3) : " opcion
					echo ""

		# ----- Asignar el atributo basado en la opción elegida
						case "$opcion" in

							1)
							# ----- Cambiar el cn
							        read -p "   Introduzca el nuevo CN: " nuevo_cn
							        echo ""

							# ----- Renombrar el grupo usando ldapmodrdn
							        ldapmodrdn -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" "cn=$cn,$GRUPOS,$BASE_DN" "cn=$nuevo_cn"

								        if [ $? -eq 0 ]; then
								            echo -e "${g} El cn del grupo ha sido cambiado de '$cn' a '$nuevo_cn'.${nc}"
								            echo ""
								        else
								            echo -e "${r} Error al cambiar el cn del grupo $cn.${nc}"
								        fi

							# ----- Creación del archivo de modificación para sustituir el atributo antiguo 'cn' por el nuevo.
							
								    	 	echo -e "${y} Sustituyendo atributo cn antigüo por cn nuevo...${nc}"
												echo "dn: cn=$nuevo_cn,ou=grupos,$BASE_DN" > "$CAMBIOS_FILE"
												echo "changetype: modify" >> "$CAMBIOS_FILE"
												echo "replace: cn" >> "$CAMBIOS_FILE"
												echo "cn: $nuevo_cn" >> "$CAMBIOS_FILE" 
								            
												ldapmodify -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$CAMBIOS_FILE"
							# ----- Si no hiciesemos esto nos aparecerían el cn antiguo y el cn nuevo en el atributo cn.
							            ;;

							2)
								   	atributo="ou"
								    ;;
							3)
									atributo="description"
            						;;
							*)
								    echo -e "${r} Error: Opción no válida.${nc}"
								    return
								    ;;
						esac
					
			
		# ----- Solicitud nuevo valor del atributo
					if [ -n "$atributo" ];then
					echo ""
						read -p "  Introduzca el nuevo valor para $atributo : " nuevo_valor

		# ----- Creación del archivo de modificación.
						echo "dn: cn=$cn,ou=grupos,$BASE_DN" > "$CAMBIOS_FILE"
						echo "changetype: modify" >> "$CAMBIOS_FILE"
						echo "replace: $atributo" >> "$CAMBIOS_FILE"
						echo "$atributo: $nuevo_valor" >> "$CAMBIOS_FILE" 

						echo ""
						echo -e "${y} Procesando archivo cambios.ldif... ${nc}"
						echo ""

		# ----- Contenido archivo cambios.ldif
						echo " Contenido de cambios.ldif:"
						echo ""
						cat "$CAMBIOS_FILE"
						echo ""
					
		# ----- Modificación de los atributos del usuario leyendo archivo cambios.ldif.
						ldapmodify -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$CAMBIOS_FILE"

		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
			    		if [ $? -eq 0 ]; then
			        		echo -e "${g} $atributo del grupo: $cn modificado.${nc}"
			        		echo ""			    			
			    		else
			    			echo""
			        		echo -e "${r} Error al modificar el $atributo del grupo: $cn.${nc}"
			    		fi
			    	fi

		# Limpiar archivo cambios.ldif
						> "$CAMBIOS_FILE"
		    		
		}
#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para eliminar un grupo.
#--------------------------------------------------------------------------------------------------------------------------
	eliminar_grupo(){
			echo ""
			echo -e "${b} Eliminación de un grupo${nc}"
			echo ""

		# ----- Solicitar información al usuario 
			echo ""
			read -p " Introduzca el nombre del grupo (cn) a eliminar: " cn

		# ----- Verificar que el grupo existe antes de eliminar
		    			if ! existe_grupo "$cn"; then
		        			echo""
		        			echo -e "${r}Error: El grupo '$cn' no existe.${nc}"
		        			return
		    			fi
		
		# ----- Obtener miembros del grupo
					    miembros=$(ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "$GRUPOS,$BASE_DN" "cn=$cn" memberUid | grep '^memberUid:')

		# ----- Mostrar miembros
					echo ""
				    echo -e "${y} El grupo '$cn' contiene los siguientes miembros:${nc}"

				    if [ -z "$miembros" ]; then
				    	echo ""
				        echo " No contiene miembros."
				    else
				        echo "  $miembros" | sed 's/^memberUid: //'
				    fi

				    echo ""
				    echo -e "${g} Aunque elimine el grupo los usuarios no serán eliminados.${nc}"

						# ----- Pregunta de verificación de la eliminación.
									echo ""
									read -p " ¿Está seguro que desea eliminar el grupo '$cn'? (s/n) : " respuesta

											if [[ "$respuesta" =~ ^[Ss]$ ]];then
												echo ""
												ldapdelete -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" "cn=$cn,ou=grupos,$BASE_DN"
											else
												echo ""
						    					echo -e "${r} Eliminación cancelada${nc}"
												exit 0
											fi
		   
		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
			    		if [ $? -eq 0 ]; then
			        		echo -e "${g} Grupo $cn eliminado.${nc}"
			    		else
			    			echo""
			        		echo -e "${r} Error al eliminar el grupo $cn.${nc}"
			    		fi
		}

#--------------------------------------------------------------------------------------------------------------------------
# -------------------------------------------- FUNCIONES PARA OU ----------------------------------------------------------

# ----- Función para comprobar si existe el unidad organizativa.
#--------------------------------------------------------------------------------------------------------------------------
	existe_ou(){
		local ou=$1	
			ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=$ou,$BASE_DN" "(&(objectClass=organizationalUnit)(ou=$ou))" > /dev/null 2>&1
		}

# ----- Función para la creación de unidades organizativas.
#--------------------------------------------------------------------------------------------------------------------------
	crear_ou(){
			echo ""
			echo -e "${b} Creación de una nueva Unidad Organizativa (OU)${nc}"
			echo ""

		# ----- Solicitar información al usuario
				    read -p " Introduce el nombre de la OU: " ou
				   	echo ""

		# ----- Verificar si la ou existe antes de crear
			    			if existe_ou "$ou"; then
			        			echo -e "${r} Error: La OU '$ou' ya existe.${nc}"
			        			return
			    			fi

				    read -p " Introduce una descripción(opcional): " descripcion

    	# ----- Crear el archivo LDIF

    	  				if [ -f "$LDIF_OU" ]; then
        					echo "El archivo '$LDIF_OU' ya existe. Se eliminará su contenido previo."
        					> "$LDIF_OU"  # Vaciar el contenido del archivo
    					else
        					touch "$LDIF_OU"  # Crear el archivo si no existe
    					fi
			    
			    {
				        echo "dn: ou=$ou,$BASE_DN"
				        echo "objectClass: organizationalUnit"
				        echo "ou: $ou"
				        if [ -n "$descripcion" ]; then
				            echo "description: $descripcion"
				        fi
				} > "$LDIF_OU"

    	# ----- Mostrar el contenido del archivo LDIF
				    echo ""
				    echo "Contenido del archivo ou.ldif:"
				    cat "$LDIF_OU"
				    echo ""

				    echo -e "${y} Procesando archivo ou.ldif.${nc}" 
				    echo ""

    	# ----- Añadir la OU usando ldapadd
    				ldapadd -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$LDIF_OU"

		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
					if [ $? -eq 0 ]; then
						echo ""
						echo -e "${g} Nueva unidad organizativa '$ou' creada correctamente.${nc}"

					else
						echo""
						echo -e "${r} Error al crear la nueva unidad organizativa '$ou'"${nc}
					fi			   
	}

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para modificar OU.
#--------------------------------------------------------------------------------------------------------------------------
	modificar_ou(){
		echo ""
		echo -e "${b} Creación de una nueva Unidad Organizativa (OU)${nc}"
		echo ""
			
			CAMBIOS_FILE="cambios.ldif"

		# ----- Si el archivo cambios.ldif no existe crearlo.
					if [ ! -f "$CAMBIOS_FILE" ]; then
						touch "$CAMBIOS_FILE"
					fi

		# ----- Introducir ou como parámetro de búsqueda.			
					echo ""
					read -p " Introduce el nombre de la OU a modificar : " ou

		# ----- Verificar que la ou existe antes de modificar.
		    		if ! existe_ou "$ou"; then
		        		echo""
		        		echo -e ${r}" Error: La OU '$ou' no existe.${nc}"
		        		return
		        	else
		        		echo ""
		        		echo -e "${g} La OU existe${nc}"
		    		fi

		# ----- Menú de atributos a modificar
					echo ""
					echo -e "${y} Atributos disponibles para modificar: ${nc}"
					echo ""

						echo "  1) Nombre de la OU (ou)"
   						echo "  2) Descripción"
    					echo "  3) Salir"

					echo ""
					read -p " Introduzca el número de atributo que desea modificar: " opcion

					case $opcion in
				        1)
							echo ""
							read -p " Introduzca el nuevo nombre para la OU: " nueva_ou

				            # ----- Renombrar la OU usando ldapmodrdn
							        ldapmodrdn -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" "ou=$ou,$BASE_DN" "ou=$nueva_ou"

								        if [ $? -eq 0 ]; then
								        	echo ""
								            echo -e "${g} El nombre de la OU se ha cambiado de '$ou' a '$nueva_ou'.${nc}"
								            echo ""
								        else
								            echo -e "${r} Error al cambiar el nombre de la OU '$ou'.${nc}"
								        fi

							# ----- Creación del archivo de modificación para sustituir el atributo antiguo 'cn' por el nuevo.
							
								    	 	echo -e "${y} Sustituyendo atributo ou antigüo por ou nuevo...${nc}"
								    	 	echo ""
												echo "dn: ou=$nueva_ou,$BASE_DN" > "$CAMBIOS_FILE"
												echo "changetype: modify" >> "$CAMBIOS_FILE"
												echo "replace: ou" >> "$CAMBIOS_FILE"
												echo "ou: $nueva_ou" >> "$CAMBIOS_FILE" 

							# ----- Modificación 	            
												ldapmodify -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$CAMBIOS_FILE" 
							# ----- Si no hiciesemos esto nos aparecerían el ou antiguo y el ou nuevo en el atributo ou.
							            ;;
				        2)
				            atributo="description"
				            ;;
				        *)
				            echo "Operación no válida."
				            return
				            ;;
				    esac

		# ----- Solicitud nuevo valor en el caso de atributos diferentes al nombre de la OU
					echo ""
   					read -p " Introduzca el nuevo valor para $atributo: " nuevo_valor

		# ----- Creación del archivo de modificación.
					echo "dn: ou=$ou,$BASE_DN" > "$CAMBIOS_FILE"
					echo "changetype: modify" >> "$CAMBIOS_FILE"
					echo "replace: $atributo" >> "$CAMBIOS_FILE"
					echo "$atributo: $nuevo_valor" >> "$CAMBIOS_FILE" 

					echo ""
					echo -e "${g} Procesando archivo cambios.ldif... ${nc}"
					echo ""
					
		# ----- Modificación de los atributos del usuario leyendo archivo cambios.ldif.
					ldapmodify -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -f "$CAMBIOS_FILE" > /dev/null 2>&1  # ----- Redirección para descartar el resultado de la salida del comando  

		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
			    		if [ $? -eq 0 ]; then			        		
			        		echo -e "${g} Atributo de la OU '$ou' modificado exitosamente.${nc}"			    			
			    		else
			    			echo""
			        		echo -e "${r} Error al modificar el atributo de la OU '$ou'.${nc}"
			    		fi

		    		> "$CAMBIOS_FILE"
	}

#--------------------------------------------------------------------------------------------------------------------------
# ----- Función para eliminar OU.
#--------------------------------------------------------------------------------------------------------------------------
	eliminar_ou(){
		echo ""
		echo -e "${b} Eliminar Unidad Organizativa (OU)${nc}"

		# ----- Solicitud de nombre de OU.
			echo""
			read -p " Introduzca el nombre de la unidad organizativa(OU) a eliminar: " ou

		# ----- Verificar que la OU existe antes de eliminar	
		    			if ! existe_ou "$ou"; then
		        			echo""
		        			echo -e ${r}" Error: La OU '$ou' no existe.${nc}"
		        			return
		    			fi
		# ----- Mostrar contenido de la OU 
			echo ""
			echo -e "${r} La OU '$ou' que pretende eliminar contiene: ${nc}"

		listar_contenido() {
			local ou=$1
				    
		# ----- Listar usuarios de la OU.
		    	echo -e "${y} Usuarios de la OU '$ou'${nc}"
		    	echo ""
		   	 		ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=$ou,$BASE_DN" "(objectClass=posixAccount)" uid | grep '^uid:' | sed 's/^uid: //'

		# ----- Listar grupos de la OU.
		    	echo -e "${y} Grupos de la OU '$ou'${nc}"
		    	echo ""
		    		ldapsearch -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" -b "ou=$ou,$BASE_DN" "(objectClass=posixGroup)" cn | grep '^cn:' | sed 's/^cn: //'
		}
		
		# ----- Eliminar OU de LDAP
					echo ""
					read -p "Está apunto de eliminar la OU $ou. ¿Esta seguro? (s/n):" respuesta

					if [[ $respuesta =~ ^[sS]$ ]];then
		    			ldapdelete -x -D "$ADMIN_DN" -w "$ADMIN_PW" -H "$LDAP_SERVER" "ou=$ou,$BASE_DN"
		# ----- Verificación si el comando anterior se ha ejecutado correctamente.  
			    		if [ $? -eq 0 ]; then			  
			        		echo ""
			        		echo -e "${g}Unidad organizativa '$ou' eliminada exitosamente.${nc}"			    			
			    		else
			    			echo""
			        		echo -e "${r}Error al eliminar la unidad organizativa '$ou'.${nc}"
			    		fi
		    		else
		    			echo ""
		    			echo -e "${r} Eliminación cancelada${nc}"
		    		fi
		    
		
	}
#--------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------- Menú selección creación de objetos ---------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------			
	crear_objeto(){
			while true; do
			    	echo ""
					echo -e "${y}Seleccione el tipo de objeto a crear : ${nc}"

						echo ""
						echo "  1. Usuario"
						echo "  2. Grupo"
						echo "  3. Unidad Organizativa"
						echo "  4. Volver al menú principal"
						echo ""
						read -p "Seleccione una opción [1-4] : " tipo

							case $tipo in 

								1)
									crear_usuario
									;;
								2)
									crear_grupo
									;;
				        		3)
									crear_ou
									;;
								4)
									return
									;;
								*)
									echo "Opción inválida"
									;;
							esac
			done
		}
#--------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------ Menú selección modificación de objetos ---------------------------------------
#--------------------------------------------------------------------------------------------------------------------------	        
	modificar_objeto(){
			while true; do  
					echo ""
					echo -e "${y}Seleccione el tipo de objeto a modificar : ${nc}"

						echo ""
						echo "  1. Usuario"
						echo "  2. Grupo"
						echo "  3. Unidad Organizativa"
						echo "  4. Volver al menú principal"
						echo ""
						read -p "Seleccione una opción [1-4] : " tipo

							case $tipo in 

								1)
									modificar_usuario
									;;
								2)
									modificar_grupo
									;;
				        		3)
									modificar_ou
									;;
								4)
									return
									;;
								*)
									echo "Opción inválida"
									;;
							esac
			done
		}
#--------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------- Menú selección eliminación de objetos -----------------------------------------	
#--------------------------------------------------------------------------------------------------------------------------	              
	eliminar_objeto(){
			while true; do
					echo""
					echo -e "${y}Seleccione el tipo de objeto a eliminar : ${nc}"
					echo""

						echo "  1. Usuario"
						echo "  2. Grupo"
						echo "  3. Unidad Organizativa"
						echo "  4. Volver al menú principal"
						echo""
						read -p "Seleccione una opción [1-4] : " tipo

							case $tipo in 

								1)
									eliminar_usuario
									;;
								2)
									eliminar_grupo
									;;
				        		3)
									eliminar_ou
									;;
								4)
									return
									;;
								*)
									echo "Opción inválida"
									;;
							esac
			done
		}
#--------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------------ MENÚ PRINCIPAL ---------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------------
			while true; do				
					echo ""
					echo -e "${b}================================================="

						echo -e "   MENÚ DE ADMINISTRACIÓN DE SERVIDOR OpenLDAP"

					echo -e "=================================================${nc}"

						echo ""
						echo -e " ${y}Seleccione una opción:${nc}"
						echo ""
						echo "  1. Agregar objeto"
						echo "  2. Modificar objeto"
						echo "  3. Eliminar objeto"
						echo "  4. Salir"
						echo ""
						read -p  "Seleccione una opción [1-4] : " opcion

							case $opcion in

								1)
									crear_objeto
									;;
								2)
									modificar_objeto
									;;
								3)
									eliminar_objeto
									;;
							    4)
									echo "Saliendo..."
									exit 0
									;;
							    *)
							        echo "Opción inválida"
							        ;;
							esac
			done
